phraseapp:
    project_id: 5092d10a50efbcdb78684023d60c0f91
    push:
      sources:
      - file: ./ICE-Scarlet/<locale_code>.yml
        params:
          file_format: strings
          update_translations: true
    pull:
      targets:
      - file: ./ICE-Scarlet/<locale_code>.yml
        params:
          file_format: strings
